# Generated by Django 3.1.4 on 2021-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_visit', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('tenth', models.CharField(max_length=40)),
                ('twelth', models.CharField(max_length=40)),
                ('graduate', models.CharField(max_length=40)),
                ('stream', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('visa_date_applied', models.CharField(max_length=40)),
                ('visa_date_recieved', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
